Red Hat: yaboot-1.3.13-pegasos-ext2.patch
https://github.com/gooselinux/yaboot/

diff --git a/ybin/ybin b/ybin/ybin
--- a/ybin/ybin
+++ b/ybin/ybin
@@ -77,6 +77,8 @@ if (cat /proc/cpuinfo 2> /dev/null | grep ^platform | grep -q 'pSeries') ; then
     fstype=raw
 elif (cat /proc/cpuinfo 2> /dev/null | grep ^platform | grep -q 'PowerNV') ; then
     fstype=raw
+elif (cat /proc/cpuinfo 2> /dev/null | grep ^machine | grep -q 'Pegasos') ; then
+    fstype=ext2
 else
     fstype=hfs
 fi
@@ -281,13 +283,13 @@ checkconf()
     fi
 
     case "$fstype" in
-	hfs|msdos|raw)
+	hfs|msdos|raw|ext2)
 	 ;;
 	*)
 	 if [ "$ARGFS" = 1 ] ; then
-	    echo 1>&2 "$PRG: --filesystem must be either \`hfs', \`msdos', or \`raw'"
+	    echo 1>&2 "$PRG: --filesystem must be either \`hfs', \`msdos', \`ext2' or \`raw'"
 	 else
-	    echo 1>&2 "$PRG:$ERR \`fstype' must be either \`hfs', \`msdos', or \`raw'"
+	    echo 1>&2 "$PRG:$ERR \`fstype' must be either \`hfs', \`msdos', \`ext2' or \`raw'"
 	 fi
 	 local CONFERR=1
 	 ;;
@@ -950,12 +952,16 @@ util_install()
 ## used by mnt_install so mntpoint= can be supported in a cleaner way.
 mnt()
 {
+    local mountopts="rw"
+
     ## we can even create bootstrap filesystem images directly if you
     ## ever wanted too.
     if [ -f "$boot" ] ; then
-	local loop=",loop"
+	mountopts="$mountopts,loop"
     fi
-
+    if [ "$fstype" = "msdos" ] ; then
+	mountopts="$mountopts,umask=077"
+    fi
     if [ -e "$TMP/bootstrap.$$" ] ; then
 	echo 1>&2 "$PRG: $TMP/bootstrap.$$ exists, aborting."
 	return 1
@@ -974,7 +980,7 @@ mnt()
     fi
 
     [ "$VERBOSE" = 1 ] && echo "$PRG: Mounting $boot..."
-    mount -t "$fstype" -o rw,umask=077$loop "$boot" "$TMP/bootstrap.$$"
+    mount -t "$fstype" -o "$mountopts" "$boot" "$TMP/bootstrap.$$"
     if [ $? != 0 ] ; then
 	echo 1>&2 "$PRG: An error occured mounting $boot"
 	return 1
@@ -1257,6 +1263,25 @@ mkoffs()
 	    mkdosfs -n bootstrap "$boot" > /dev/null
             if [ $? != 0 ] ; then
 		echo 1>&2 "$PRG: DOS filesystem creation failed!"
+		return 1
+	    fi
+	    return 0
+	    ;;
+	ext2)
+	    if (command -v mkfs.ext2 > /dev/null 2>&1) ; then
+		[ -x `command -v mkfs.ext2` ] || FAIL=1 ; else FAIL=1 ; fi
+		if [ "$FAIL" = 1 ] ; then
+		    echo 1>&2 "$PRG: mkfs.ext2 is not installed or cannot be found"
+		    return 1
+		fi
+
+	    [ "$VERBOSE" = 1 ] && echo "$PRG: Creating ext2 filesystem on $boot..."
+	    if (command -v dd > /dev/null 2>&1) ; then
+		dd if=/dev/zero of="$boot" bs=512 count=1600 > /dev/null 2>&1
+	    fi
+	    mkfs.ext2 -L bootstrap "$boot" > /dev/null
+	    if [ $? != 0 ] ; then
+		echo 1>&2 "$PRG: ext2 filesystem creation failed!"
 		return 1
 	    fi
 	    return 0
